import mongoose from 'mongoose';
const Schema = mongoose.Schema;

const orderSchema = new Schema({
  _id: { type: Number, required: true, index: { unique: true } },
  shop: { type: String, required: true },
  couponSent: { type: Boolean, default: false },

  billing_address: {
    address1: { type: String, default: null },
    address2: { type: String, default: null },
    city: { type: String, default: null },
    company: { type: String, default: null },
    country: { type: String, default: null },
    first_name: { type: String, default: null },
    id: { type: Number, default: 0 },
    last_name: { type: String, default: null },
    phone: { type: String, default: null },
    province: { type: String, default: null },
    zip: { type: String, default: null },
    name: { type: String, default: null },
    province_code: { type: String, default: null },
    country_code: { type: String, default: null },
    default: { type: Boolean, default: false },
    district: { type: String, default: null },
    district_code: { type: String, default: null },
  },
  browser_ip: { type: String, default: null },
  buyer_accepts_marketing: { type: Boolean, default: false },
  cancel_reason: { type: String, default: null },
  cancelled_at: { type: Date, default: null },
  cart_token: { type: String, default: null },
  checkout_token: { type: String, default: null },
  client_details: {
    accept_language: { type: String, default: null },
    browser_ip: { type: String, default: null },
    session_hash: { type: String, default: null },
    user_agent: { type: String, default: null },
    browser_height: { type: String, default: null },
    browser_width: { type: String, default: null },
  },
  closed_at: { type: Date, default: null },
  created_at: { type: Date, default: null },
  created_at_utc7: { type: Date, default: null },
  currency: { type: String, default: null },
  customer: {
    accepts_marketing: { type: Boolean, default: false },
    addresses: [],
    created_at: { type: Date, default: null },
    default_address: Schema.Types.Mixed,
    email: { type: String, default: null },
    first_name: { type: String, default: null },
    id: { type: Number, default: 0 },
    multipass_identifier: { type: String, default: null },
    last_name: { type: String, default: null },
    last_order_id: { type: Number, default: 0 },
    last_order_name: { type: String, default: null },
    note: { type: String, default: null },
    orders_count: { type: Number, default: 0 },
    state: { type: String, default: null },
    tags: { type: String, default: null },
    total_spent: { type: Number, default: 0 },
    updated_at: { type: Date, default: null },
    verified_email: { type: Boolean, default: false },
    send_email_invite: { type: Boolean, default: false },
    send_email_welcome: { type: Boolean, default: false },
    password: { type: String, default: null },
    password_confirmation: { type: String, default: null },
    group_name: { type: String, default: null },
  },
  discount_codes: [],
  email: { type: String, default: null },
  financial_status: { type: String, default: null },
  fulfillments: [],
  fulfillment_status: { type: String, default: null },
  tags: { type: String, default: null },
  gateway: { type: String, default: null },
  gateway_code: { type: String, default: null },
  landing_site: { type: String, default: null },
  landing_site_ref: { type: String, default: null },
  ref: { type: String, default: null },
  source: { type: String, default: null },
  line_items: [],
  name: { type: String, default: null },
  note: { type: String, default: null },
  number: { type: Number, default: 0 },
  order_number: { type: String, default: null },
  processing_method: { type: String, default: null },
  referring_site: { type: String, default: null },
  refunds: [],
  shipping_address: {
    address1: { type: String, default: null },
    address2: { type: String, default: null },
    city: { type: String, default: null },
    company: { type: String, default: null },
    country: { type: String, default: null },
    first_name: { type: String, default: null },
    last_name: { type: String, default: null },
    latitude: { type: Number, default: 0 },
    longitude: { type: Number, default: 0 },
    phone: { type: String, default: null },
    province: { type: String, default: null },
    zip: { type: String, default: null },
    name: { type: String, default: null },
    province_code: { type: String, default: null },
    country_code: { type: String, default: null },
    district_code: { type: String, default: null },
    district: { type: String, default: null },
  },
  shipping_lines: [],
  source_name: { type: String, default: null },
  subtotal_price: { type: Number, default: 0 },
  tax_lines: { type: String, default: null },
  taxes_included: { type: Boolean, default: false },
  token: { type: String, default: null },
  total_discounts: { type: Number, default: 0 },
  total_line_items_price: { type: Number, default: 0 },
  total_price: { type: Number, default: 0 },
  total_tax: { type: Number, default: 0 },
  total_weight: { type: Number, default: 0 },
  updated_at: { type: Date, default: null },
  transactions: [],
  note_attributes: [],
  confirmed_at: { type: Date, default: null },
  order_cancel_note: { type: String, default: null },
  user_id: { type: Number, default: null },
  username: { type: String, default: null },
  device_id: { type: Number, default: null },
  location_id: { type: Number, default: null },
  ref_order_id: { type: Number, default: null },
  ref_order_number: { type: String, default: null },
}, {
  timestamps: {},
});

orderSchema.index({ shop: 1 });

export default mongoose.model('Order', orderSchema);
